version: '3.0'
services:
  lib_db:
    container_name: 'lib_db'
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      lib_newtork:
networks:
  lib_newtork: