"""empty message

Revision ID: 80c24a5ea566
Revises: 4dca93f6957c
Create Date: 2023-10-05 21:30:30.721730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c24a5ea566'
down_revision: Union[str, None] = '4dca93f6957c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###
