"""empty message

Revision ID: 8c8393e4f215
Revises: 3fdf4777fb8d
Create Date: 2023-10-04 19:33:19.068351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8393e4f215'
down_revision: Union[str, None] = '3fdf4777fb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UsersBooks_book_fkey', 'UsersBooks', type_='foreignkey')
    op.create_foreign_key(None, 'UsersBooks', 'Accounting', ['book'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UsersBooks', type_='foreignkey')
    op.create_foreign_key('UsersBooks_book_fkey', 'UsersBooks', 'Books', ['book'], ['id'])
    # ### end Alembic commands ###
